#!/usr/bin/env python
import re
import os
import sys
import getopt
import subprocess
from subprocess import Popen, PIPE

import ConfigParser
from jira.client import JIRA

def config():
    config = ConfigParser.ConfigParser()
    config.read(['.jira.cfg', os.path.expanduser('~/.jira.cfg')])
    return {
        'JIRA' : {
            'hostname': config.get('JIRA', 'hostname'),
            'username': config.get('JIRA', 'username'),
            'password': config.get('JIRA', 'password')
        },
        'pattern': {
            'branch': config.get('Pattern', 'branch', 1),
            'message': config.get('Pattern', 'message', 1),
        }
    }

def curr_branch():
    p = Popen(['git', 'branch'], stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, err = p.communicate()

    for row in output.split("\n"):
        if row[0:1] == '*':
            return row.split(' ')[1]

def get_issue_number(branch):
    params = branch.split('_')
    issue_id = params[0]
    return issue_id

def get_commit_message(issue_id):
    # Load configuration
    cfg = config()

    # Configuration
    options = {
        'server': cfg['JIRA']['hostname']
    }

    # Connect to jira
    try:
        jira = JIRA(options, basic_auth=(cfg['JIRA']['username'], cfg['JIRA']['password']), validate=True)
    except Exception, e:
        print "Error occured, are you sure you can connect to JIRA server?"
        sys.exit(5)

    # Message template
    msg = cfg['pattern']['message']
    try:
        # Get issue information
        issue = jira.issue(issue_id)

        # Extract items from issue info
        story_name = issue.fields.summary
        print vars(issue)

        # Replace patterns in branch name
        msg = msg.replace('%(issue_id)', str(issue_id))
        msg = msg.replace('%(story_name)', story_name)

    except Exception, e:
        print "Error occured, are you sure your config, or branch name is correct?"
        sys.exit(4)

    return msg

def main():
    # Get default file content
    f = open(sys.argv[1], 'r')
    msg = f.read()
    f.close()

    if (msg.startswith('Merge branch')):
        return 0

    # Get current branch
    branch = curr_branch()

    # Get current issue
    issue_id = get_issue_number(branch)

    # Get commit message
    commit_msg = get_commit_message(issue_id)

    # Rewrite file prepending the message
    f = open(sys.argv[1], 'w')
    f.write(commit_msg)
    f.write(msg)
    f.close()

if __name__ == "__main__":
    main()
